export const ProblemOverview1 = "Washington State legislative assistants (LAs) are overwhelmed by constituent inquiries and face challenges responding in a timely and thorough manner.  Some LAs receive 100s of inquiries daily about various topics, ranging from House Bills to questions about citizenship. Due to this high volume of messages, LAs often do not get the chance to respond to all their constituents, creating a lack of engagement between the people and their representatives.";
export const ProblemOverview2 = "How might LAs better communicate with constituents and handle responses to improve transparency and increase engagement?";
export const ProblemOverview3 = "Existing platforms and technologies for LAs to filter and respond to their inquiries do not supply the necessary functionality to effectively and efficiently organize and display incoming messages. As such, our team wanted to create a new solution that caters directly to the specific needs of LAs and helps them to categorize messages while improving response times. With more efficiency on the LAs’ side, more constituents receive responses and more time can be allocated to helping constituents in other ways.";

export const TargetStakeholders1 = "Legislative Assistants and the representatives they work with are the target stakeholders for this project, with the LAs themselves as the primary users. Although this is a very niche group of users, we believe that their challenges with handling constituent responses is a problem space that is often overlooked. ";
export const TargetStakeholders2 = "If this project is adopted by another team in the future, we hope that it can be expanded and tailored to several different types of users and occupations. Many of the functions and features of Civic QA are specific to LAs but could also serve useful for many others, including teachers, organizers, CEOs, etc. ";

export const Solution1 = "Through extensive user research and competitive analysis, Civic QA has built an efficient and comprehensive third-party communication tool to manage constituent relations. Our process for creating this platform can be broken down into a few main steps:";
export const Solution2 = "We aim to make LAs’ jobs easier by removing some of the tediousness of their current system and making it so they can respond to constituents faster, while also gaining a better understanding of their engagement levels. We leverage machine learning to effectively categorize correspondence and help legislative assistants quickly respond to pressing issues, while enabling staff to track constituent engagement over time. By supplying engagement reports, daily trends, and filtered topics, staff have greater insight into the needs of constituents to drive better policy responses.";
export const Solution3 = "With improved responsiveness and greater overall efficiency, LAs will be able to communicate with constituents more effectively, likely encouraging more people to engage, as LAs will be more reliable and likely to respond."

export const LiaBio = "Lia is graduating with the Informatics HCI track and a Spanish Minor. Her passion lies in the intersection of art, technology, and contributing to the “social good”. She plans on working in UX/UI Design, focusing on making the future of tech more accessible and accommodating for all. In her free time you can find her jamming to Taylor Swift or practicing film photography.";
export const RafiBio = "Rafi is graduating with a degree in Informatics, following a custom track. After graduation, Rafi will be joining Microsoft as a software engineer, working with the Azure Networking team. Rafi is also interested in teaching and technical education, and hopes to use his skills to reduce the barriers to entry in the field of software. Outside of work and school, he enjoys BJJ, running, and travel. ";
export const AmitBio = "Amit is graduating with a double degree in Informatics and Biology (Molecular & Cellular). He will be starting work as a full-time software engineer at Amazon this summer. He is enthusiastic about building software that can improve people's daily life. During his free time Amit loves to either play or watch soccer, specifically his favorite team Chelsea FC.";
export const VivianBio = "Vivian is graduating with a degree in Informatics and will be working as a software engineer at Microsoft. She is passionate about women of color in tech and leadership roles. Vivian loves playing games, reading, and learning Chinese in her free time.";

export const ProjectStatus = "We are open-sourcing our project and also opening it to any future Informatics Capstone teams to take on. You can see our code and software architecture at our GitHub repo ";