# things to replace: <PATH TO main.go>

# build stage: has everything needed to build an executable
FROM golang:latest AS build-env
ADD . /src
RUN cd /src/<PATH TO main.go> && go build -o goapp

# run stage
FROM golang:latest
WORKDIR /app
COPY --from=build-env /src/<PATH TO main.go>/goapp /app/
ENTRYPOINT ["./goapp"]